spring.datasource.url=jdbc:sqlserver://107.23.31.226:1433;databaseName=proyecto_db;encrypt=false
spring.datasource.username=sa
spring.datasource.password=TuPassword123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.port=8080
